import ContactPageCompo from "@/components/ContactPage";
import { Metadata } from "next";
import { AiFillGithub } from "react-icons/ai";
import Link from "next/link";
export const metadata: Metadata = {
  title: "contact",
  description: "Generated by create next app",
};
const Links = [
  {
    icon: <AiFillGithub />,
    url: "https://github.com/nam9nine",
  },
];
export default function ContactPage() {
  return (
    <section className="flex flex-col items-center">
      <h1 className="my-2 text-3xl font-bold">Contact</h1>
      <p>Southgyuios19@gmail.com</p>
      <div className="my-4">
        {Links.map((link) => (
          <Link key={link.url} className=" text-5xl" href={link.url}>
            {link.icon}
          </Link>
        ))}
      </div>

      <h2 className="my-8 text-3xl font-bold">Or Send me an email</h2>
      <ContactPageCompo />
    </section>
  );
}
